---

- name: Fetch the certificate bundle and store it
  get_url:
    url: "{{ papertrail_rsyslog_tls_cert_bundle_url }}"
    dest: "{{ papertrail_rsyslog_tls_cert_bundle_download_path }}"
  delegate_to: 127.0.0.1
  become: no

- name: Stat the bundle
  stat:
    get_checksum: yes
    get_md5: yes
    path: "{{ papertrail_rsyslog_tls_cert_bundle_download_path }}"
  register: papertrail_rsyslog_tls_cert_bundle_download
  delegate_to: 127.0.0.1
  run_once: true
  become: no

- name: Compare the bundle variable now to the checksum to save copying to the server
  fail:
    msg: "The certificate bundle does not match the expected checksum {{ papertrail_rsyslog_tls_cert_bundle_checksum }}"
  delegate_to: 127.0.0.1
  run_once: true
  when: |
    papertrail_rsyslog_tls_cert_bundle_checksum is defined
    and papertrail_rsyslog_tls_cert_bundle_download.stat.md5 != papertrail_rsyslog_tls_cert_bundle_checksum

- name: Copy the bundle into position
  copy:
    src:    "{{ papertrail_rsyslog_tls_cert_bundle_download_path }}"
    dest:   "{{ papertrail_rsyslog_tls_cert_bundle_path }}"
    mode:   "{{ papertrail_rsyslog_tls_cert_bundle_mode }}"
    owner:  "{{ papertrail_rsyslog_tls_cert_bundle_owner }}"
    group:  "{{ papertrail_rsyslog_tls_cert_bundle_group  }}"

- set_fact:
    papertrail_rsyslog_tls_cert_bundle_do_not_use_var: yes
...
